import type { TopicId } from './library';

export interface Podcast {
  topic: TopicId;
  /** id do programa no Spotify (open.spotify.com/show/ID) */
  spotifyId: string;
  title: string;
  host: string;
  /** capa vinda do oEmbed do Spotify */
  thumb: string;
  desc: string;
}

/** Podcasts em português, IDs conferidos via oEmbed do Spotify em 01/10/2026. */
export const PODCASTS: Podcast[] = [
  { topic: "emocional", spotifyId: "6UpJb8VGuMKQT8ZKUPGfr0", title: "Psicologia na Prática", host: "Alana Anijar", thumb: "https://image-cdn-fa.spotifycdn.com/image/ab6772ab000015bea149fc1b3621dc69c19599a3", desc: "A psicologia aplicada ao dia a dia para lidar melhor com ansiedade, autoestima e emoções." },
  { topic: "emocional", spotifyId: "3l28wC5LyiiW2EdxgKW1cE", title: "Autoconsciente Podcast | Vida interior", host: "Regina Giannetti", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015bec0138bf6b6df9b6b577ce35b", desc: "Entender a própria mente, diminuir a autocobrança e viver com mais leveza." },
  { topic: "emocional", spotifyId: "5vLv8tZMOsid9WXYiRy3il", title: "Mentemania", host: "Dra. Ana Beatriz Barbosa Silva", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1fb59528223362ec35d8425b8d", desc: "Uma psiquiatra explica de forma acessível o comportamento humano e a saúde mental." },
  { topic: "financas", spotifyId: "0UR7uvXIwzbEiSLZlrp9Na", title: "PoupeCast", host: "Me Poupe! (Nathalia Arcuri)", thumb: "https://image-cdn-fa.spotifycdn.com/image/ab67656300005f1ffa534fc2145732d3e7d4ffee", desc: "Educação financeira descomplicada para sair das dívidas, poupar e começar a investir." },
  { topic: "financas", spotifyId: "0OKark671tCbUyszCSs5Ff", title: "Stock Pickers", host: "InfoMoney", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f101b8f6382d6397bb598c913", desc: "Gestores e analistas mostram como pensam e investem no mercado de ações." },
  { topic: "financas", spotifyId: "2gCj9YG9tjMexhS4pIlRHo", title: "PrimoCast", host: "Grupo Primo (Thiago Nigro)", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015be65551343d5d75d52aa4cab2a", desc: "Conversas sobre investimentos, dinheiro e empreendedorismo com grandes nomes do mercado." },
  { topic: "desenvolvimento", spotifyId: "17bkR8GX6FmyKYvhQv4nOi", title: "Os Sócios Podcast", host: "Bruno Perini e Malu Perini", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015bec53ef7cc69db860cfc2ebcf0", desc: "Lições de livros e convidados sobre desenvolvimento pessoal, saúde, finanças e vida a dois." },
  { topic: "desenvolvimento", spotifyId: "6wqBtC9OMq2mLvhDjZbqVM", title: "Jota Jota Podcast", host: "Joel Jota", thumb: "https://image-cdn-fa.spotifycdn.com/image/ab6772ab000015be4dce1e685f55521c406623fb", desc: "Hábitos, disciplina e mentalidade de alta performance para crescer na vida e na carreira." },
  { topic: "desenvolvimento", spotifyId: "39IqvZCSC52QAehb4b4aaR", title: "Mamilos", host: "Juliana Wallauer e Cris Bartis (B9)", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015bec3585100cc182baff7be6b68", desc: "Conversas abertas e respeitosas para entender melhor o mundo e a si mesmo." },
  { topic: "oratoria", spotifyId: "0DLo0QoWorKjuzFYwj5IvK", title: "Falando Bem", host: "Bianca Aydos", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015bed2fd6f334ef4226ea4ba0957", desc: "Dicas de uma fonoaudióloga para ganhar confiança e se comunicar melhor em público." },
  { topic: "oratoria", spotifyId: "6XfrEkmCxosm65PMwSMujf", title: "El Professor da Oratória", host: "Giovanni Begossi", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015beb12ff5a1b9876a2d0f0164ad", desc: "Técnicas de oratória, carisma e persuasão para falar com mais impacto." },
  { topic: "oratoria", spotifyId: "7kuL4Vn3UX99PAkCiFg0bg", title: "Oratória – Dominando a Arte de Falar em Público", host: "Juliana Salois", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015bec47657d0fc4a773ac39bebd2", desc: "Passo a passo prático para perder o medo e fazer apresentações mais seguras." },
  { topic: "lideranca", spotifyId: "5HoZGHqVtcHOjshdhdBWWU", title: "Café com ADM", host: "Leandro Vieira (Administradores.com)", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015bef7aa1785a71506289d41ec6c", desc: "Ideias de gestão, liderança e negócios com empresários e especialistas." },
  { topic: "lideranca", spotifyId: "48ljM9qIbODhemJ7lLGjeR", title: "Do Zero ao Topo", host: "InfoMoney", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f4675b2ccbc3685dc05cf64be", desc: "Histórias dos líderes por trás de grandes empresas e o que aprenderam no caminho." },
  { topic: "lideranca", spotifyId: "3uVMgk495LAALdXG4MEtiD", title: "Bate Ponto: Carreira, Liderança e Gestão de Pessoas", host: "Sólides", thumb: "https://image-cdn-fa.spotifycdn.com/image/ab6772ab000015be47fe7c937d6fb4ce07b92964", desc: "Estratégias reais de liderança, gestão de pessoas e carreira contadas por quem lidera." },
  { topic: "lideranca", spotifyId: "10hInKuRTrITavE1KLe6Yx", title: "exame.carreiras", host: "Exame", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f50b01374ef1b8b711f7bcd70", desc: "Carreira, mercado de trabalho e liderança com especialistas e executivos." },
  { topic: "produtividade", spotifyId: "1nuFSa15qyDWQ4kY9kOwRD", title: "Sai da Média", host: "Geronimo Theml e Paty Araújo", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015be638f60d8c32775fd0df4c4bf", desc: "Técnicas de foco, hábitos e produtividade para vencer a procrastinação." },
  { topic: "produtividade", spotifyId: "4hP6XOduJZfuAPwWxV2335", title: "Organiza Cast", host: "Thais Godinho (Vida Organizada)", thumb: "https://image-cdn-fa.spotifycdn.com/image/ab67656300005f1f62785824d09b561b4f57ab2f", desc: "Métodos práticos para organizar a rotina, as tarefas e a vida com mais clareza." },
  { topic: "produtividade", spotifyId: "1R6vnIvB5T6gcMvTvmBJnj", title: "Produtividade Sem Neura", host: "Marcela Lamastra", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f8b80c5b346f6a582fcdd781f", desc: "Produtividade com equilíbrio: render mais sem abrir mão da saúde mental." },
  { topic: "relacionamentos", spotifyId: "1592iJQt0IlC5u5lKXrbyS", title: "Bom dia, Obvious", host: "Marcela Ceribelli", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015be09bd245cd35310e549e8bc02", desc: "Conversas sinceras sobre relacionamentos, autoestima, afetos e bem-estar." },
  { topic: "relacionamentos", spotifyId: "0a5IW5X0pJTBXyhT7uaJjV", title: "Paizinho, Vírgula! – Família e Infância", host: "Thiago Queiroz", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab6772ab000015be237020b4fb77f5bb8b252823", desc: "Parentalidade com disciplina positiva, criação com apego e paternidade ativa." },
  { topic: "relacionamentos", spotifyId: "0mwkh4mDZdr6XSu8QWNsMK", title: "Papo de Mãe", host: "Papo de Mãe", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1ffa8460e85f4f10ca20ffc011", desc: "Histórias e conselhos práticos para mães e pais na criação dos filhos." },
  { topic: "proposito", spotifyId: "7J0DFQBIcVN9tM950CaoWw", title: "Café Filosófico CPFL", host: "Instituto CPFL", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f6f6bb912531344a80fa3db26", desc: "Grandes pensadores refletem sobre questões da vida à luz da filosofia." },
  { topic: "proposito", spotifyId: "2Yk1btoIXthB9TGp1JHQVV", title: "Prazer, Karnal", host: "Leandro Karnal", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f72dfe6921335130c3a519fa4", desc: "Reflexões de história e filosofia para pensar valores, sentido e escolhas." },
  { topic: "proposito", spotifyId: "7wOMHiiHQFRtysLqwu1uke", title: "Meditação Guiada por Marina Gutemberg", host: "Marina Gutemberg", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1fde61e1073bca0897da67f683", desc: "Meditações guiadas curtas para acalmar a mente e se reconectar consigo." },
  { topic: "proposito", spotifyId: "6LauTuWrpz39P22GhAeSzn", title: "Prática Estoica", host: "Prática Estoica", thumb: "https://image-cdn-fa.spotifycdn.com/image/ab6772ab000015be9df417c588a88dcaac5bbde2", desc: "O estoicismo aplicado à vida real: serenidade, virtude e foco no que depende de você." },
  { topic: "saude", spotifyId: "5SWaT0blo4yKdyTJ51sM9o", title: "DrauzioCast", host: "Drauzio Varella", thumb: "https://image-cdn-fa.spotifycdn.com/image/ab67656300005f1fcc05806131c18cdfb87423d5", desc: "Informação médica clara sobre prevenção de doenças e hábitos que fazem diferença." },
  { topic: "saude", spotifyId: "0BOKgZSHjBl2DNBiMbRFqs", title: "Bem-Estar", host: "g1 / TV Globo", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f22cc32fc45de8bdaae373e21", desc: "Especialistas explicam como cuidar da saúde e da qualidade de vida." },
  { topic: "saude", spotifyId: "2HagpPwVrRkgiSAsFfgMxX", title: "Alimente: Nutrição e Ciência", host: "Profa. Aline de Aguiar e Prof. Renato Nunes", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1fd36f505faa600be0486801f2", desc: "Nutrição baseada em ciência para comer melhor sem cair em modismos." },
  { topic: "lazer", spotifyId: "1EAAAOIGupWaGwidmMTTi0", title: "Naruhodo", host: "Ken Fujioka e Altay de Souza (B9)", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f8cc6fb647c4ae60aab7750b4", desc: "Ciência e curiosidades explicadas de um jeito leve para quem gosta de aprender." },
  { topic: "lazer", spotifyId: "6ICqNBFodd0NB2zLf0IQPn", title: "30:MIN – Livros e Literatura", host: "30:MIN", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f130461e040be5cf02c4c7f3b", desc: "Indicações e conversas sobre livros para reacender o hábito da leitura." },
  { topic: "lazer", spotifyId: "5FN1BLdgT0R4K8WhXOtcCx", title: "Rádio Novelo Apresenta", host: "Branca Vianna (Rádio Novelo)", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1fc40af7f7b2c3eafb324f322e", desc: "Histórias reais surpreendentes e muito bem contadas." },
  { topic: "lazer", spotifyId: "0dchxFRUOrHdeILWAjLqob", title: "Escriba Café", host: "Christian Gurtner", thumb: "https://image-cdn-ak.spotifycdn.com/image/ab67656300005f1f81dcc75c909fbb90adc4c1af", desc: "Histórias da história, da filosofia e das religiões narradas como um bom audiolivro." },
];
